accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView

app_name = 'accounts'
urlpatterns = [
    path('homepage/', views.HomepageView.as_view(), name='homepage'),
    # path('', views.index, name='index'),
    
    #Profile
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('request/list', views.requestListView.as_view(), name='requestList'),
]

quicktutor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # change the path of the google login page to be something other than the homepage
    path('', TemplateView.as_view(template_name = "accounts/google_login.html")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
#import datetime

from django.db import models
#from django.utils import timezone
from django.urls import reverse
from django.forms import ModelForm

from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
SUBJECT_CHOICES = (
    ('Subject','SUBJECT'),
    ('APMA', 'Math'),
    ('CS', 'Computer Science'),
    ('COMM', 'Business'),
    ('BIOL', 'Biology'),
    ('CHEM', 'Chemistry'),
)
TIME_INTERVALS = (
    ('5','5 minutes'),
    ('15','15 minutes'),
    ('30','35 minutes'),
    ('60','1 hour'),
    ('75','1 hour 15 minutes'),
    ('90','1.5 hour'),
    ('120','2 hours'),
)

class Homepage(models.Model):
    name = models.CharField(max_length=50,default='')
    location = models.CharField(max_length=50, default='')
    subject = models.CharField(max_length=17, choices=SUBJECT_CHOICES, default='Subject')
    courseNumber = models.CharField(max_length=50, default='')
    time = models.CharField(max_length=17, choices=TIME_INTERVALS, default='5')
    description = models.TextField(max_length=300, default='')

    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse('accounts:homepage')

class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete = models.CASCADE)
    year = models.CharField(max_length=100, blank=True)
    major = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Homepage, UserProfile

class HomepageForm(ModelForm):
    class Meta:
        model = Homepage
        fields = ['subject']

# class RegistrationForm(UserCreationForm):
#     email = forms.EmailField(required=True)

#     class Meta:
#         model = User
#         fields = (
#             'username',
#             'first_name',
#             'last_name',
#             'email',
#             'password1',
#             'password2'
#         )

#     def save(self, commit=True):
#         user = super(RegistrationForm, self).save(commit=False)
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.email = self.cleaned_data['email']

#         if commit:
#             user.save()

#         return user

class EditProfileForm(UserChangeForm):
    template_name='/something/else'
    password = None

    class Meta:
        model = User
        fields = (
            #'email',
            'first_name',
            'last_name',
            #'password'
        )

class MoreUserInfo(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['year', 'major', 'description']

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import HomepageForm, EditProfileForm, MoreUserInfo

from django.views import generic
from .models import Homepage, UserProfile
from django.shortcuts import redirect

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.
class HomepageView(generic.CreateView):
    model = Homepage
    #form_class = HomepageForm
    template_name = 'accounts/homepage.html'
    fields = ['name', 'location', 'subject', 'courseNumber', 'time', 'description']
    #success_url = 'myapp/success.html'

# def register(request):
#     if request.method =='POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse('accounts:home'))
#     else:
#         form = RegistrationForm()

#         args = {'form': form}
#         return render(request, 'accounts/reg_form.html', args)

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html')

def edit_profile(request):
    try:
        user_instance = UserProfile.objects.get(user = request.user)
    except UserProfile.DoesNotExist:
        user_instance = UserProfile(user=request.user)
    if request.method == 'POST':
        user_form = EditProfileForm(request.POST, instance=user_instance)
        info_form = MoreUserInfo(request.POST, instance=user_instance)
        if user_form.is_valid() and info_form.is_valid():
            user_form.save()
            info_form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        user_form = EditProfileForm(instance=request.user)
        info_form = MoreUserInfo(instance=request.user)
        # args = {'form': form}
        return render(request, 'accounts/edit_profile.html', {'user_form': user_form,'info_form':info_form})

class requestListView(generic.ListView):
    model = Homepage
    template_name = 'accounts/requestList.html'

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% bootstrap_messages %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Profile</h1>
    <h3>Student</h3>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ user_form|crispy}}
        {{ info_form|crispy }}
        <br>
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/google_login.html
{% load socialaccount %}
{% providers_media_js %}

<html>
    <head>
        <title>Login with Google!</title>
    </head>

    <body>
        <a href="{% provider_login_url 'google' %}">Login with Google!</a>
    </body>
</html>

accounts/templates/accounts/homepage.html
{% load crispy_forms_tags %}

<div id="header" class="header">
	<div class="row">
		<div class="col-lg-6 col-md-6">
		<center>
		<h1>Homepage</h1>
			<p>Send a tutor request!</p></center>
		</div>
	</div>
</div>
<hr>
<style>
	body{
		background-color: #33ACFF;
	}
</style>
<center>
<form action="" method="post">{% csrf_token %}
	{{ form|crispy }}
	<br>
    <input type="submit" value="Request" />
</form>
</center>
<hr>
<div class="container">
	<footer>
		<center>
		<p>
			Copyright 2020, Style group
		</p>
		<p>
			Footer made on 2020-02-20 12:35
		</p>
		</center>
	</footer>
</div>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% bootstrap_messages %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <h3>Student</h3>
    <br>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <p>Year: {{ user.userprofile.year }}</p>
    <p>Major: {{ user.userprofile.major }}</p>
    <p>About: {{ user.userprofile.description }}</p>
    <br>
    <a href="{% url 'accounts:edit_profile'%}">Edit Profile</a>
</div>

{% endblock %}

accounts/templates/accounts/requestList.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<div id="header" class="header">
	<div class="row">
		<div class="col-lg-6 col-md-6">
			<center>
		<h1>Requests</h1>
				<p>This website is a list of student requests</p></center>
		</div>
	</div>
</div>
<hr>
<body>
	<style>
		body{
		background-color: #33ACFF
		}
	</style>
	<center>
	<p>NAME | LOCATION | SUBJECT</p>
	{% for homepage in object_list %}
        <li>{{ homepage.name }} | {{ homepage.location}} | {{ homepage.subject}}</li>
    {% endfor %}
</body>
</center>
<hr>
<div class="container">
	<footer>
		<center>
		<p>
			Copyright 2020, Style Group
		</p>
		<p>
			Footer made on 2020-02-22 11:46
		</p>
		</center>
	</footer>
</div>